CREATE TABLE owners(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(255),
status INT NOT NULL DEFAULT 0, 
last_update DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_by VARCHAR(255),
PRIMARY KEY (id));

CREATE TABLE notices(
id INT NOT NULL AUTO_INCREMENT,
owner_id INT,
content VARCHAR(255),
last_update DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_by VARCHAR(255),
PRIMARY KEY (id));
